### PR TITLE
Add video

### PR DESCRIPTION
**Pull request by basimkarhabi**
I had add the link for video in frontend 
make an private area for wokshops it work after login

### CODE REVIEW

**Review by Doven-Obertinca — APPROVED** [review]

**Review by fuad221 — APPROVED** [review]

**Comment by fuad221** [comment]
ok

**Comment by basimkarhabi** [comment]
ok

**Review by Iandraws — APPROVED** [review]

**Comment by Iandraws** [comment]
hghfgg

**Comment by basimkarhabi** [comment]
ok

**Pull request merged**
